[options]
colorscheme = "gruvbox"
colorscheme_bg = "dark"
autocomplete_method = "coc"

[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lang#ruby'